package model.db;

public class SQLStrings {

	public static final String DB_CREATE = "CREATE DATABASE ";

	public static final String DB_RENAME = "ALTER DATABASE %s RENAME TO %s";

	public static final String DB_LIST = "SELECT datname FROM pg_database WHERE datistemplate = false";

	public static final String[] TABLES_CREATE = {
			"CREATE TABLE IF NOT EXISTS PESSOAS (ID SERIAL NOT NULL PRIMARY KEY, IDENTIFICADOR VARCHAR(11), "
					+ "NOME VARCHAR(100), TIPO INTEGER);",

			"CREATE TABLE IF NOT EXISTS LOCAIS (ID SERIAL NOT NULL PRIMARY KEY, "
					+ "NOME VARCHAR(100), CAPACIDADE INTEGER, TIPO INTEGER, NUM_COMP INTEGER);",

			"CREATE TABLE IF NOT EXISTS CURSOS (ID SERIAL NOT NULL PRIMARY KEY, "
					+ "NOME VARCHAR(100), HORARIO VARCHAR(100), DURACAO INTEGER, TIPO INTEGER, PALESTRANTE INTEGER REFERENCES PESSOAS(ID), "
					+ "LOCAL INTEGER REFERENCES LOCAIS(ID));",

			"CREATE TABLE IF NOT EXISTS PARTICIPANTES_CURSO (ID SERIAL NOT NULL, CURSO INTEGER NOT NULL REFERENCES CURSOS(ID), "
					+ "PARTICIPANTE INTEGER NOT NULL REFERENCES PESSOAS(ID));",

			"CREATE TABLE IF NOT EXISTS PARTICIPANTES_PRESENCA (ID SERIAL NOT NULL, CURSO INTEGER NOT NULL REFERENCES CURSOS(ID), "
					+ "PARTICIPANTE INTEGER NOT NULL REFERENCES PESSOAS(ID));" };

	public static final String INSERT_PESSOA = "INSERT INTO PESSOAS (IDENTIFICADOR, NOME, TIPO) "
			+ "VALUES ('%s', '%s', %d) RETURNING ID;";

	public static final String INSERT_LOCAL = "INSERT INTO LOCAIS (NOME, CAPACIDADE, TIPO, NUM_COMP) "
			+ "VALUES ('%s', %d, %d, %d) RETURNING ID;";

	public static final String INSERT_CURSO = "INSERT INTO CURSOS (NOME, HORARIO, DURACAO, TIPO, PALESTRANTE, LOCAL) "
			+ "VALUES ('%s', '%s', %d, %d, %d, %d) RETURNING ID;";

	public static final String INSERT_PART_CURSO = "INSERT INTO PARTICIPANTES_CURSO (CURSO, PARTICIPANTE) "
			+ "VALUES (%d, %d) RETURNING ID;";

	public static final String INSERT_PRES_CURSO = "INSERT INTO PARTICIPANTES_PRESENCA (CURSO, PARTICIPANTE) "
			+ "VALUES (%d, %d) RETURNING ID;";

	public static final String UPDATE_PESSOA = "UPDATE PESSOAS SET IDENTIFICADOR = '%s', NOME = '%s' WHERE ID = %d";

	public static final String UPDATE_LOCAL = "UPDATE LOCAIS SET NOME = '%s', CAPACIDADE = %d, NUM_COMP = %d WHERE ID = %d";

	public static final String UPDATE_CURSO = "UPDATE CURSOS SET NOME = '%s', HORARIO = '%s', DURACAO = %d, TIPO = %d, PALESTRANTE = %d, LOCAL = %d WHERE ID = %d";

	public static final String SELECT_PESSOA = "SELECT * FROM PESSOAS WHERE ID = %d";

	public static final String SELECT_LOCAL = "SELECT * FROM LOCAIS WHERE ID = %d";

	public static final String SELECT_CURSO = "SELECT * FROM CURSOS WHERE ID = %d";

	public static final String SELECT_PART_CURSO = "SELECT DISTINCT CURSO, PARTICIPANTE FROM PARTICIPANTES_CURSO WHERE CURSO = %d";

	public static final String SELECT_PRES_CURSO = "SELECT PARTICIPANTE FROM PARTICIPANTES_PRESENCA WHERE CURSO = %d";

	public static final String SELECT_ALL_LOCAL = "SELECT * FROM LOCAIS";

	public static final String SELECT_ALL_ID_CURSO = "SELECT ID FROM CURSOS";

	public static final String SELECT_ALL_ID_PESSOA = "SELECT ID FROM PESSOAS";

	public static final String SELECT_CURSOS_FROM_PESSOA = "SELECT DISTINCT CURSO FROM PARTICIPANTES_CURSO WHERE PARTICIPANTE = %d";

}
